### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by n0bodysec** [n0bodysec/Fuzion#2]
Please keep all feature request in comments instead of opening a new issue. Thanks.

**Format (really?)**
```
**Feature:** ...
**Description:** ...
Anything you want.
```

~~I don't know why I'm writing this, since nobody will read this.~~

**Comment by acuifex** [comment]
Working desync please <3

**Comment by n0bodysec** [comment]
Ok, I'll try.

**Comment by Zedespook** [comment]
**Feature:** Back- and forward tracking
**Description:** Back-tracking and forward-tracking in HvH and Legit would be a nice addition to the cheat.

**Comment by Zedespook** [comment]
**Feature:** Infinite crouch bug
**Description:** This is really easy to do, I know. You just use bullrush and all. But you could make the auto-crouch feature just a little better. Maybe put a "Bugged" tickbox under "Auto-Crouch" in the HvH tab.

**Comment by Zedespook** [comment]
**Feature:** Better resolver
**Description:** Looking into the code, you can see that the current resolver randomly picks a + and - desync amount 66% from the position they are in. I don't know about you, but I think this isn't really enough, at least when I tried it didn't seem to really resolve. I may suggest that the value may be set by the user, or just code a whole different resolver after all.

**Comment by n0bodysec** [comment]
@Zedespook:

1. **Back- and forward tracking**: Would be nice. Also backtracking has legit implementations. What do you mean by "forward tracking"?

2. **Infinite crouch bug**: Yap, just IN_BULLRUSH shit. I think I will do this right now cuz it's the easiest request.

3. **Better resolver**: Yeah, I noticed! I'll try!

Thanks!

**Comment by Zedespook** [comment]
@n0bodysec https://www.youtube.com/watch?v=066rFX2cibM Here's a video about forward-tracking, I don't know if it helps or not.

Also, I actually had a third person fix, sadly I lost the source code for it, but I pasted it from `asdasdhook`, that was the only source that didn't use sv_cheat spoofing. So I guess you can start from there if you need some help. But if you paste that source, then the character will flicker on the server what the user hosts, but on other servers, third-person looks just fine. (Also, AA didn't show on that source in tp).

Hope I helped. Thank you for your response!

**Comment by n0bodysec** [comment]
Thanks for the vid!

I think the easiest/"best" method is actually spoof sv_cheats, also I can paste my fix from my Windows internal, but I'm looking for a "best" method.

Thanks for ur help!
Regards.

**Comment by acuifex** [comment]
> Working desync please <3

I started to think that lwss made working fakes but fucked up fake angles sending?
i was toggled flipper on actual with bot mimic and bot stayed like nothing happened
but when i toggled flipper on fakes they are now my fakes and my reals (tested in hvh but not with my friend)

**Comment by Zedespook** [comment]
By the way, not really an issue with the cheat itself, but how are you going to manage with new messages in one thread? Like after a while you're gonna have to go from page to page to just see the newest message, or you have a good method to it?

**Comment by n0bodysec** [comment]
@Zedespook as repo owner, I can "hide" comments also I can delete them.

**Comment by n0bodysec** [comment]
Infinite crouch bug aka no duck cooldown added! Thanks @Zedespook.

Also I will close this thread since has no sense (https://github.com/n0bodysec/Fuzion/issues/2#issuecomment-493710326).

Open new issues instead!

Thanks.
