### ISSUE TITLE
[Bug] Clan-tag changer works, but glitches the game.

### ISSUE THREAD

**Issue by Zedespook** [n0bodysec/Fuzion#5]
So when I have it on, the game starts to have these weird lag-glitches. Can't really explain, but it just doesn't work,  the only way to use the clan-tag changer is to just set it to static with the desired clan-tag you want to use, and turn it off immediately.

**Comment by n0bodysec** [comment]
I'm aware of that. Anyway, thanks for the issue!
Also I need to know if namechanger work. It works?

Regards.

**Comment by acuifex** [comment]
> Also I need to know if namechanger work. It works?

No

**Comment by n0bodysec** [comment]
Thanks again for the issue.

I'm checking why occurs this "lag".
Also Name Changer doesn't work (I think it's because change callback is now CUtilVector).

**Comment by n0bodysec** [comment]
I think LWSS fixed this issue in the latest Fuzion update.
